CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(100) NOT NULL,
    `company_id` INT NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `created_time` DATETIME DEFAULT CURRENT_TIMESTAMP
);
