sys.http.listen=8082
sys.https.listen=
sys.jdbc.password=root
sys.jdbc.url=jdbc:mysql://localhost:3306/meeting_room?useSSL=false&serverTimezone=UTC
sys.jdbc.user=root
sys.kafka.url=localhost:9092
sys.log.appender=console